// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: eye_tracker.proto
#ifndef GRPC_eye_5ftracker_2eproto__INCLUDED
#define GRPC_eye_5ftracker_2eproto__INCLUDED

#include "eye_tracker.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace eye_tracker {

// Define gRPC service
class EyeTrackerService final {
 public:
  static constexpr char const* service_full_name() {
    return "eye_tracker.EyeTrackerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>> StreamEyeData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>>(StreamEyeDataRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>> AsyncStreamEyeData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>>(AsyncStreamEyeDataRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>> PrepareAsyncStreamEyeData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>>(PrepareAsyncStreamEyeDataRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamEyeData(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::eye_tracker::EyeData,::eye_tracker::FatigueAlert>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* StreamEyeDataRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* AsyncStreamEyeDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* PrepareAsyncStreamEyeDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>> StreamEyeData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>>(StreamEyeDataRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>> AsyncStreamEyeData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>>(AsyncStreamEyeDataRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>> PrepareAsyncStreamEyeData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>>(PrepareAsyncStreamEyeDataRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamEyeData(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::eye_tracker::EyeData,::eye_tracker::FatigueAlert>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* StreamEyeDataRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* AsyncStreamEyeDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* PrepareAsyncStreamEyeDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamEyeData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamEyeData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamEyeData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamEyeData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamEyeData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEyeData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamEyeData(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamEyeData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamEyeData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamEyeData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamEyeData(context); }));
    }
    ~WithCallbackMethod_StreamEyeData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEyeData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* StreamEyeData(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StreamEyeData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamEyeData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamEyeData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamEyeData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEyeData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamEyeData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamEyeData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamEyeData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEyeData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamEyeData(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamEyeData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamEyeData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamEyeData(context); }));
    }
    ~WithRawCallbackMethod_StreamEyeData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEyeData(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamEyeData(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace eye_tracker


#endif  // GRPC_eye_5ftracker_2eproto__INCLUDED
