// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: eye_tracker.proto

#include "eye_tracker.pb.h"
#include "eye_tracker.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace eye_tracker {

static const char* EyeTrackerService_method_names[] = {
  "/eye_tracker.EyeTrackerService/StreamEyeData",
};

std::unique_ptr< EyeTrackerService::Stub> EyeTrackerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EyeTrackerService::Stub> stub(new EyeTrackerService::Stub(channel, options));
  return stub;
}

EyeTrackerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamEyeData_(EyeTrackerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* EyeTrackerService::Stub::StreamEyeDataRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>::Create(channel_.get(), rpcmethod_StreamEyeData_, context);
}

void EyeTrackerService::Stub::async::StreamEyeData(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::eye_tracker::EyeData,::eye_tracker::FatigueAlert>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::eye_tracker::EyeData,::eye_tracker::FatigueAlert>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamEyeData_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* EyeTrackerService::Stub::AsyncStreamEyeDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>::Create(channel_.get(), cq, rpcmethod_StreamEyeData_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>* EyeTrackerService::Stub::PrepareAsyncStreamEyeDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>::Create(channel_.get(), cq, rpcmethod_StreamEyeData_, context, false, nullptr);
}

EyeTrackerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EyeTrackerService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< EyeTrackerService::Service, ::eye_tracker::EyeData, ::eye_tracker::FatigueAlert>(
          [](EyeTrackerService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::eye_tracker::FatigueAlert,
             ::eye_tracker::EyeData>* stream) {
               return service->StreamEyeData(ctx, stream);
             }, this)));
}

EyeTrackerService::Service::~Service() {
}

::grpc::Status EyeTrackerService::Service::StreamEyeData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::eye_tracker::FatigueAlert, ::eye_tracker::EyeData>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace eye_tracker

